const GET_NFT_DETAIL_LOADING = 'GET_NFT_DETAIL_LOADING'
const GET_NFT_DETAIL_SUCCESS = 'GET_NFT_DETAIL_SUCCESS'
const GET_NFT_DETAIL_FAILURE = 'GET_NFT_DETAIL_FAILURE'
const UPDATE_NFT_DETAIL_LOADING = 'UPDATE_NFT_DETAIL_LOADING'
const UPDATE_NFT_DETAIL_SUCCESS = 'UPDATE_NFT_DETAIL_SUCCESS'
const UPDATE_NFT_DETAIL_FAILURE = 'UPDATE_NFT_DETAIL_FAILURE'
const CLEAR_NFT_DETAIL = 'CLEAR_NFT_DETAIL'
const GET_TRADING_HISTORY_LOADING = 'GET_TRADING_HISTORY_LOADING'
const GET_TRADING_HISTORY_SUCCESS = 'GET_TRADING_HISTORY_SUCCESS'
const GET_TRADING_HISTORY_FAILURE = 'GET_TRADING_HISTORY_FAILURE'

export const collectibleActions = {
  GET_NFT_DETAIL_LOADING,
  GET_NFT_DETAIL_SUCCESS,
  GET_NFT_DETAIL_FAILURE,
  UPDATE_NFT_DETAIL_LOADING,
  UPDATE_NFT_DETAIL_SUCCESS,
  UPDATE_NFT_DETAIL_FAILURE,
  CLEAR_NFT_DETAIL,
  GET_TRADING_HISTORY_LOADING,
  GET_TRADING_HISTORY_SUCCESS,
  GET_TRADING_HISTORY_FAILURE,
}
