const DEPLOY_SUCCESS = 'DEPLOY_SUCCESS'
const DEPLOY_PENDING = 'DEPLOY_PENDING'
const DEPLOY_FAILED = 'DEPLOY_FAILED'

const CREATE_PENDING = 'CREATE_PENDING'
const CREATE_SUCCESS = 'CREATE_SUCCESS'
const CREATE_FAILED = 'CREATE_FAILED'

const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_SUCCESS'

const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS'
export const collectionActions = {
    DEPLOY_SUCCESS,
    DEPLOY_PENDING,
    DEPLOY_FAILED,
    CREATE_SUCCESS,
    CREATE_FAILED,
    CREATE_PENDING,
    CREATE_COLLECTION_SUCCESS,
    GET_COLLECTION_SUCCESS
}
