const LOGIN_LOADING = 'LOGIN_LOADING'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILURE = 'LOGIN_FAILURE'

const CLICK_BTN_CREATE = 'CLICK_BTN_CREATE'
const SIGN_WITH_CREATE = 'SIGN_WITH_CREATE'

const OPEN_LOADING_CONNECT = 'OPEN_LOADING_CONNECT'
const CLOSE_LOADING_CONNECT = 'CLOSE_LOADING_CONNECT'

export const loginApiActions = {
  LOGIN_LOADING,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  CLICK_BTN_CREATE,
  SIGN_WITH_CREATE,
  OPEN_LOADING_CONNECT,
  CLOSE_LOADING_CONNECT,
}
