const TERM_OF_SERVICE_OPEN = 'TERM_OF_SERVICE_OPEN'
const TERM_OF_SERVICE_CLOSE = 'TERM_OF_SERVICE_CLOSE'

const WRONG_NETWORK_OPEN = 'WRONG_NETWORK_OPEN'
const WRONG_NETWORK_CLOSE = 'WRONG_NETWORK_CLOSE'

const REJECT_SIGN_MODAL_OPEN = 'REJECT_SIGN_MODAL_OPEN'
const REJECT_SIGN_MODAL_CLOSE = 'REJECT_SIGN_MODAL_CLOSE'

const USER_CLOSED_MODAL_OPEN = 'USER_CLOSED_MODAL_OPEN'
const USER_CLOSED_MODAL_CLOSE = 'USER_CLOSED_MODAL_CLOSE'

const LOCK_METAMASK_MODAL_OPEN = 'LOCK_METAMASK_MODAL_OPEN'
const LOCK_METAMASK_MODAL_CLOSE = 'LOCK_METAMASK_MODAL_CLOSE'

const REJECT_CONNECT_MODAL_OPEN = 'REJECT_CONNECT_MODAL_OPEN'
const REJECT_CONNECT_MODAL_CLOSE = 'REJECT_CONNECT_MODAL_CLOSE'

export const modalAction = {
  TERM_OF_SERVICE_OPEN,
  TERM_OF_SERVICE_CLOSE,
  WRONG_NETWORK_OPEN,
  WRONG_NETWORK_CLOSE,
  REJECT_SIGN_MODAL_OPEN,
  REJECT_SIGN_MODAL_CLOSE,
  USER_CLOSED_MODAL_OPEN,
  USER_CLOSED_MODAL_CLOSE,
  LOCK_METAMASK_MODAL_OPEN,
  LOCK_METAMASK_MODAL_CLOSE,
  REJECT_CONNECT_MODAL_OPEN,
  REJECT_CONNECT_MODAL_CLOSE,
}
