const USER_LOGIN_WALLET_LOADING = 'USER_LOGIN_WALLET_LOADING'
const USER_LOGIN_WALLET_SUCCESS = 'USER_LOGIN_WALLET_SUCCESS'
const USER_LOGIN_WALLET_FAILURE = 'USER_LOGIN_WALLET_FAILURE'
const USER_LOGOUT_WALLET = 'USER_LOGOUT_WALLET'

const USER_EDIT_PROFILE_LOADING = 'USER_EDIT_PROFILE_LOADING'
const USER_EDIT_PROFILE_SUCCESS = 'USER_EDIT_PROFILE_SUCCESS'
const USER_EDIT_PROFILE_FAILURE = 'USER_EDIT_PROFILE_FAILURE'

const USER_GET_PROFILE_LOADING = 'USER_GET_PROFILE_LOADING'
const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS'
const USER_GET_PROFILE_FAILURE = 'USER_GET_PROFILE_FAILURE'

const USER_SET_UPDATE_PROFILE_STATE = 'USER_SET_UPDATE_PROFILE_STATE'

const USER_UPLOAD_AVATAR_LOADING = 'USER_UPLOAD_AVATAR_LOADING'
const USER_UPLOAD_AVATAR_SUCCESS = 'USER_UPLOAD_AVATAR_SUCCESS'
const USER_UPLOAD_AVATAR_FAILURE = 'USER_UPLOAD_AVATAR_FAILURE'

const USER_UPLOAD_COVER_LOADING = 'USER_UPLOAD_COVER_LOADING'
const USER_UPLOAD_COVER_SUCCESS = 'USER_UPLOAD_COVER_SUCCESS'
const USER_UPLOAD_COVER_FAILURE = 'USER_UPLOAD_COVER_FAILURE'

const USER_UPLOAD_COLLECTION_COVER_LOADING = 'USER_UPLOAD_COLLECTION_COVER_LOADING'
const USER_UPLOAD_COLLECTION_COVER_SUCCESS = 'USER_UPLOAD_COLLECTION_COVER_SUCCESS'
const USER_UPLOAD_COLLECTION_COVER_FAILURE = 'USER_UPLOAD_COLLECTION_COVER_FAILURE'

const UPDATE_BALANCE = 'UPDATE_BALANCE'

const GET_CURRENT_USER_PROFILE = 'GET_CURRENT_USER_PROFILE'

export const userActions = {
    USER_LOGIN_WALLET_LOADING,
    USER_LOGIN_WALLET_SUCCESS,
    USER_LOGIN_WALLET_FAILURE,
    USER_LOGOUT_WALLET,
    USER_EDIT_PROFILE_LOADING,
    USER_EDIT_PROFILE_SUCCESS,
    USER_EDIT_PROFILE_FAILURE,
    USER_GET_PROFILE_LOADING,
    USER_GET_PROFILE_SUCCESS,
    USER_GET_PROFILE_FAILURE,
    USER_SET_UPDATE_PROFILE_STATE,
    USER_UPLOAD_AVATAR_LOADING,
    USER_UPLOAD_AVATAR_SUCCESS,
    USER_UPLOAD_AVATAR_FAILURE,
    USER_UPLOAD_COVER_LOADING,
    USER_UPLOAD_COVER_SUCCESS,
    USER_UPLOAD_COVER_FAILURE,
    USER_UPLOAD_COLLECTION_COVER_LOADING,
    USER_UPLOAD_COLLECTION_COVER_SUCCESS,
    USER_UPLOAD_COLLECTION_COVER_FAILURE,
    UPDATE_BALANCE,
    GET_CURRENT_USER_PROFILE
}
